import type { Metadata } from "next";
import { ThemeProvider } from "@/components/themeprovider";
import "./globals.css";
import { Architects_Daughter } from "next/font/google";

const arch = Architects_Daughter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`flex justify-center items-center ${arch.variable} antialiased`}
      >
        <ThemeProvider
           attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
