import type { Metadata } from "next";

import "./globals.css";
import { Architects_Daughter } from "next/font/google";

const arch = Architects_Daughter({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center ${arch.variable} ${arch.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
